### ISSUE TITLE
Discuss enforced minimum & maximum for settle timeout for channels

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#16]
Maybe not really part of the specs, but we can provide some recommended values. This is actually quite important to decide on and maybe we should go through all `timeout` values and make sure they are ok.

uint: `number of blocks`
Currently:
`timeout >= 6 && timeout <= 2700000)`

In uRaiden we just have `>=500`.

## ToDo
- [x] Add `settle_timeout_min` and `settle_timeout_max` as constructors for the `TokenNetwork` and `TokenNetworkRegistry`
- [x] Use small timeout values for testing
- [x] Use decided values for deployment
- [x] Update constants in raiden
- [x] Update raiden proxies

**Comment by hackaugusto** [comment]
The settlement window is used to do on-chain unlocks, for the new implementation this is equivalent to registering the secret on-chain. We need to consider how many blocks does it take to register a secret under congestion, and that should be the /enforced/ minimum. The default value should be the minimum * maximum number of expected pending transfer.

**Comment by LefterisJP** [comment]
> We need to consider how many blocks does it take to register a secret under congestion

This is not an easy thing to answer. It all depends on what gas price you use and what is the average gas price in the network at the time.

In congestion what happens is that the average price just simply rises a lot and so should your offered gas price. If you don't do that then you won't be able to get a transaction mined for as long as the congestion keeps the average gas price above what you gave. This could last for weeks ... or even never get back to the original gas price you gave.

It is a very dynamic situation and depends on too many factors which we can't foresee.

For example looking at [gas station](https://ethgasstation.info/calculatorTxV.php) at the moment average gas price is 4 Gwei, cheap is 3 Gwei. With the average price, the mean time to get the transaction confirmed is `13.5 blocks`. With 3 Gwei it's 85.6 block and with 1 Gwei it's 645 blocks.

But that's just now. 3 weeks ago I sent 1 Gwei transactions (cheap) and they got mined in ~20 blocks.

I guess the point I am trying to make is that we can't really put a number to how many block it takes to register a secret under congestion. If you up the gas price enough then the average is ~10 blocks and max 30 blocks. And thats for the last months. We can't know in the future how this will evolve.

**Comment by hackaugusto** [comment]
@loredanacirstea https://github.com/raiden-network/raiden/issues/864

**Comment by LefterisJP** [comment]
So what has been decided from our quick meeting is to keep the limits **both in the contracts and in the client code**. The logic is that it's simpler to do it this way at this point and there are some open questions if we don't follow that approach.

The limits decided are :

`MAX_SETTLE_TIMEOUT` =  3 months assuming a block time of 14 seconds, so `555428` blocks
`MIN_SETTLE_TIMEOUT` = `500` blocks which with the same assumption should be close to 2 hours.

These values are experimental and we can refine them further through our test release but are probably the safest to start with.


Open Questions: If we decided to remove the checks from the contracts and keep them only client side, banning channels that have not been opened with acceptable attributes, then how do we react to someone opening a channel for us with a settlement timeout of 0? We would have to close it and then open our own channel, which would essentially open attack vectors.

**Comment by palango** [comment]
This now requires the new contracts to be deployed as we cannot change the settlement timeouts of the old contracts. Ref #1663

**Comment by palango** [comment]
Are you looking for this: https://github.com/raiden-network/raiden-contracts/blob/4e00e9ce647772a58a94c6b35992acee63f2cb40/raiden_contracts/constants.py#L38-L39

**Comment by loredanacirstea** [comment]
Yes! For some reason I did not see it when I looked for it. Thank you!
