### ISSUE TITLE
[META] Make the Raiden Spec Alderaan Release Ready

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/spec#252]
# Get to a spec to be up-to-date with Alderaan
When we Release Alderaan on Mainnet we need a Raiden Spec, that is 

- [x] up to date, i.e. every information is correct according to the current code base of the Raiden Client, the Raiden Services and the Raiden Contracts
- [x] a good read, i.e. we have examples of the data structure and the code that is used

Therefore, we need to make sure, that every chapter contains the correct information.

## Overall:
- [x] make the table of contents consistent
- [x] start every chapter with an overview like in ["Smart Contracts for Raiden Services"](https://raiden-network-specification.readthedocs.io/en/latest/service_contracts.html), i.e. start with a general explanation and the goal
- [x] ensure that every chapter has a consistent structure (start with overview or summary, then continue with ...)

## Raiden Message Specification
- [x] Raiden Message Specification has the correct data fields and tables, see e.g.https://github.com/raiden-network/spec/issues/327
- [x] Raiden Message Specification has correct, consistent and easy to read descriptions and definitions
- [x] Raiden Message Specification has a consistent example for the messages

## Raiden Transport
- [x] Make sure Raiden Transport has the correct information, data fields and tables, see https://github.com/raiden-network/spec/pull/330
- [x] Get help from at least one outsider to make this a good, consistent read

## Raiden Network Smart Contracts Specification
- [x] Make sure Raiden Network Smart Contracts Specification has the correct information, data fields and tables (coordinate with @karlb  ) https://github.com/raiden-network/spec/issues/253
- [x] Get help from at least one outsider to make this a good, consistent read

## Smart Contracts for Raiden Services
- [x] Make sure Smart Contracts for Raiden Services has the correct information, data fields and tables (coordinate with @karlb  ) https://github.com/raiden-network/spec/issues/254 and #255 

## Raiden Monitoring Service
- [x] Make sure Raiden Monitoring Service has the correct information, data fields and tables (coordinate with @palango )

## Raiden Pathfinding Service
- [x] Make sure Raiden Pathfinding Service has the correct information, data fields and tables, see #314 (coordinate with @palango )

## Mediation fees
- [x] Add information about mediation fees. See #251 
- [x] improve chapter, see #307 

## Raiden Mobile Wallet Specification
- [x] Find out who is responsible for that chapter
- [x] Delete chapter, since it is not longer maintained 

## Raiden Terminology
- [x] Make sure Raiden Terminology has the correct information, data fields and tables (coordinate with)
- [x] Delete every term from Raiden Terminology that is not used

**Comment by pirapira** [comment]
* [ ] The Solidity sources in `spec` repo needs to be updated.

**Comment by jomuel** [comment]
> * [ ]  The Solidity sources in `spec` repo needs to be updated. #255

@pirapira do you want to do this together with the other contract spec issues?

**Comment by pirapira** [comment]
Yep.

**Comment by Dominik1999** [comment]
@jomuel thank you for taking care of this. What is missing here? Can you try to update and check the tick boxes?

**Comment by jomuel** [comment]
Note on the Terminology section: Some terms that are not used in the spec, but common and useful, have been left in it. It is meant to be a glossary for the project after all, not just footnotes for the spec.
